apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  labels:
    app: webdep1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
        labels: 
          app: webapp1
    spec:
      containers:
        - name: con1
          image: pranaygupta1988/webapp1:1
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

---

apiVersion: v1
kind: Service
metadata:
  name: webser1
  labels:
    app: ser1
spec:
  type: NodePort
  selector:
    app: webapp1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31800
      protocol: TCP
